apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170987617
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170987617
    app.kubernetes.io/part-of: test-app-170987617
  name: java-quarkus-170987617
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170987617
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170987617
    spec:
      containers:
      - image: quay.io/hacdev/pyaqwvfr-tenant/test-app-170987617/java-quarkus-170987617@sha256:3f95c7c2085ed3903e907063dcfc84e8c59f94390d2d98a90a7aa2cad98cc11b
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
